### ISSUE TITLE
Expand not needed

### ISSUE THREAD

**Issue by F5OEO** [davecrump/rpidatv_local_install#1]
With Jessie image , expand is done automatically on first boot : 
you can remove 

> Log in (pi/raspberry), and type "sudo raspi-config" to open the configuration tool. Select option 1 to expand the file system to the whole disk.

**Comment by davecrump** [comment]
Agreed.  I'll remove the need to expand once I have moved the build to the new Jessie

**Comment by davecrump** [comment]
My new build at https://github.com/davecrump/rpidatv uses the 2016-11-24 Jessie Lite which self-expands, so this issue is now solved.  The need for this script has passed, so I will not maintain it.
